version: "3.9"
services:
  web:
    container_name: web-container
    build: .
    volumes:
      - .:/code 
    ports: 
      - "8000:8000"
    links:
      - bd
  bd:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=todos
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345


